apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dptest
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default # you can change the project name
  source:
    path: envs/plt/dptest1
    repoURL: https://github.com/cuotos/k8stest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
