apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-service
  project: default
  source:
    path: echo-service
    repoURL: https://github.com/cuotos/k8stest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
