apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-test
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: danp-test-pod-one
  template:
    metadata:
      name: test-pod-one
      labels:
        app: danp-test-pod-one
    spec:
      containers:
        - name: app
          image: cuotos/webtester
